### ISSUE TITLE
issue related to react Router in react js E-Commerce Application  when click with Navlinks it works fine but when App hard Refresh it redirect to root

### ISSUE THREAD

**Issue by dipakpatil5050** [dipakpatil5050/Hariba_Home_Page#2]
issue related to react Router in react js E-Commerce Application  when click with Navlinks it works fine but when App hard Refresh it redirect to root

**Comment by Amrani-Farouk-Hossam-Eddine** [comment]
Hi, i want to work on the issue

**Comment by dipakpatil5050** [comment]
sure you can

**Comment by dipakpatil5050** [comment]
resolve the issue successfully....
